name: 'Continuous Integration'
on: [push, pull_request]

jobs:
  continuousIntegration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: 'Build & Test'
        env:
          BRANCH_NAME: ${{ github.ref }}
        run: ./gradlew check -PbranchName=$BRANCH_NAME --info
      - name: 'Publish docker image'
        if: ${{ startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/heads/release') }}
        env:
          BRANCH_NAME: ${{ github.ref }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: ./gradlew pushDockerImage -PbranchName=$BRANCH_NAME --info